# Generated by Django 3.2.4 on 2021-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_1688',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data_jd',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='data_taobao',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
