# Generated by Django 3.2.4 on 2021-06-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0003_data_jd_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_jd',
            old_name='sale',
            new_name='rate',
        ),
    ]
