# Generated by Django 3.2.4 on 2021-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0004_rename_sale_data_jd_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='essencial_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jd_header', models.TextField(blank=True, default='', max_length=1000)),
                ('jd_comment_header', models.TextField(blank=True, default='', max_length=1000)),
                ('jd_comment_cookie', models.TextField(blank=True, default='', max_length=1000)),
                ('tb_header', models.TextField(blank=True, default='', max_length=1000)),
                ('pjjx_header', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='data_jd',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
